/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  MaintenanceRequest as PrismaMaintenanceRequest,
} from "@prisma/client";

export class MaintenanceRequestServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.MaintenanceRequestCountArgs, "select">
  ): Promise<number> {
    return this.prisma.maintenanceRequest.count(args);
  }

  async maintenanceRequests<T extends Prisma.MaintenanceRequestFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.MaintenanceRequestFindManyArgs>
  ): Promise<PrismaMaintenanceRequest[]> {
    return this.prisma.maintenanceRequest.findMany<Prisma.MaintenanceRequestFindManyArgs>(
      args
    );
  }
  async maintenanceRequest<T extends Prisma.MaintenanceRequestFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.MaintenanceRequestFindUniqueArgs>
  ): Promise<PrismaMaintenanceRequest | null> {
    return this.prisma.maintenanceRequest.findUnique(args);
  }
  async createMaintenanceRequest<T extends Prisma.MaintenanceRequestCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.MaintenanceRequestCreateArgs>
  ): Promise<PrismaMaintenanceRequest> {
    return this.prisma.maintenanceRequest.create<T>(args);
  }
  async updateMaintenanceRequest<T extends Prisma.MaintenanceRequestUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.MaintenanceRequestUpdateArgs>
  ): Promise<PrismaMaintenanceRequest> {
    return this.prisma.maintenanceRequest.update<T>(args);
  }
  async deleteMaintenanceRequest<T extends Prisma.MaintenanceRequestDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.MaintenanceRequestDeleteArgs>
  ): Promise<PrismaMaintenanceRequest> {
    return this.prisma.maintenanceRequest.delete(args);
  }
}
