/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MaintenanceRequest } from "./MaintenanceRequest";
import { MaintenanceRequestCountArgs } from "./MaintenanceRequestCountArgs";
import { MaintenanceRequestFindManyArgs } from "./MaintenanceRequestFindManyArgs";
import { MaintenanceRequestFindUniqueArgs } from "./MaintenanceRequestFindUniqueArgs";
import { DeleteMaintenanceRequestArgs } from "./DeleteMaintenanceRequestArgs";
import { MaintenanceRequestService } from "../maintenanceRequest.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => MaintenanceRequest)
export class MaintenanceRequestResolverBase {
  constructor(
    protected readonly service: MaintenanceRequestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "MaintenanceRequest",
    action: "read",
    possession: "any",
  })
  async _maintenanceRequestsMeta(
    @graphql.Args() args: MaintenanceRequestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [MaintenanceRequest])
  @nestAccessControl.UseRoles({
    resource: "MaintenanceRequest",
    action: "read",
    possession: "any",
  })
  async maintenanceRequests(
    @graphql.Args() args: MaintenanceRequestFindManyArgs
  ): Promise<MaintenanceRequest[]> {
    return this.service.maintenanceRequests(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => MaintenanceRequest, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MaintenanceRequest",
    action: "read",
    possession: "own",
  })
  async maintenanceRequest(
    @graphql.Args() args: MaintenanceRequestFindUniqueArgs
  ): Promise<MaintenanceRequest | null> {
    const result = await this.service.maintenanceRequest(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => MaintenanceRequest)
  @nestAccessControl.UseRoles({
    resource: "MaintenanceRequest",
    action: "delete",
    possession: "any",
  })
  async deleteMaintenanceRequest(
    @graphql.Args() args: DeleteMaintenanceRequestArgs
  ): Promise<MaintenanceRequest | null> {
    try {
      return await this.service.deleteMaintenanceRequest(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
